name: smart_state_handler
description: A comprehensive Flutter widget for handling all UI states (loading, error, success, empty, offline) with animations, overlay mode, pagination, and extensive customization options.
version: 1.0.3
homepage: https://github.com/nahidhasannoyon/smart_state_handler
repository: https://github.com/nahidhasannoyon/smart_state_handler
issue_tracker: https://github.com/nahidhasannoyon/smart_state_handler/issues
topics:
  - state-management
  - ui
  - widgets
  - flutter-package
  - animations

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
